# Network:
GENESIS_TIME: 1634900400
# Chain:
CHAIN_ID: 232
NETWORK_ID: 232
FORK_CHOICE: 0x73a55317
# Bootnodes:
PANDORA_BOOTNODES: ""
VANGUARD_BOOTNODES: ""
# Stats pages:
ETH1_STATS_URL: staging.stats.pandora.l15.lukso.network
ETH1_STATS_APIKEY:
ETH2_STATS_URL:
