# The full config options can be found here:
# https://geth.ethereum.org/docs/fundamentals/config-files

[Eth]
NetworkId = 4201


[Eth.Miner]
GasCeil = 42000000
GasPrice = 4200000000 # 4.2 Gwei


[Node]
DataDir = "./testnet-data/execution"
# IPCPath = "./testnet-data/execution/geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth", "engine"] # ["net", "eth", "web3", "debug", "engine", "txpool"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "eth", "engine"]  # ["net", "eth", "web3", "debug", "engine", "txpool"]
# GraphQLVirtualHosts = ["localhost"]

# Engine API
JWTSecret = "./configs/shared/secrets/jwt.hex"
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"] # ["*"]


[Node.P2P]
BootstrapNodes = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.141.196.212:30303","enode://ab4221c35f8cd50fb4036cc8a1f0e1b11b754416c445ce6bc02779bfa4feab4131e35ccb655c5db8999bdd1b16b70487dd74ef7a16c8065f9f81c8ab4c646f99@34.91.156.224:30303"]
BootstrapNodesV5 = []

StaticNodes = []
TrustedNodes = []

MaxPeers = 50
NoDiscovery = false
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false


[Ethstats]
# URL = "node_name@server_address"
