[Eth]
NetworkId = 4201

[Eth.Miner]
GasCeil = 600000000
GasPrice = 0 
PriceLimit = 0

[Node]
DataDir = "/mainnet-data"
JWTSecret = "/mainnet-data/jwtsecret"
# GraphQLVirtualHosts = ["localhost"]
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["net"] # ["net", "eth", "web3", "debug", "engine", "txpool"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net"] # ["net", "eth", "web3", "debug", "engine", "txpool"]
# Engine API
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["*"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
ListenAddr = ":30303"
EnableMsgEvents = false
BootstrapNodes = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.147.105.186:30303"]
BootstrapNodesV5 = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.147.105.186:30303"]

[Ethstats]
# URL = "${NODE_NAME}@${ETH_STATS_IP}"

[Metrics]
Enabled = false
HTTP = "localhost"
Port = 6060
# InfluxDBEndpoint = "http://localhost:8086"
# InfluxDBDatabase = "geth"
# InfluxDBUsername = "testuser"
# InfluxDBPassword = "testpw"
# InfluxDBTags = "host=localhost"
# InfluxDBToken = "test"
# InfluxDBBucket = "geth"
# InfluxDBOrganization = "geth"