[Eth]
NetworkId = 2022

[Eth.Miner]
GasCeil = 42000000
GasPrice = 4200000000

[Node]
DataDir = "./devnet-data/execution"
JWTSecret = "./configs/shared/secrets/jwt.hex"
IPCPath = "./devnet-data/execution/geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
AuthAddr = "localhost"
AuthPort = 8551
AuthVirtualHosts = ["localhost"]
WSHost = "localhost"
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
DiscAddr = ""
EnableMsgEvents = false

[Ethstats]
# URL = "node_name@server_address"
