# Extends the mainnet preset
PRESET_BASE: 'mainnet'
CONFIG_NAME: 'lukso'

# Genesis Start
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 120
# Sun Jan 23 2022 19:44:55 GMT+0000
MIN_GENESIS_TIME: 1673536404
# Network starts at MIN_GENESIS_TIME + GENESIS_DELAY
GENESIS_DELAY: 2400

TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x98f5fd17b9e8cbe9be6d4ee66bbfe1d8647caa053b2b426124810a0557c2525d
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# Deposit contract and execution chain IDs
# ---------------------------------------------------------------
# Custom Ethereum testnet
DEPOSIT_CHAIN_ID: 2022
DEPOSIT_NETWORK_ID: 2022
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Forks
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Gensis fork
GENESIS_FORK_VERSION: 0x20220003

# Altair
ALTAIR_FORK_VERSION: 0x20220002
ALTAIR_FORK_EPOCH: 0

# BELLATRIX
BELLATRIX_FORK_VERSION: 0x20220003
BELLATRIX_FORK_EPOCH: 0

# Capella
CAPELLA_FORK_VERSION: 0x20220003
CAPELLA_FORK_EPOCH: 1


# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 12
# 2**5 (= 32) slots 6.4 minutes
SLOTS_PER_EPOCH: 32
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 12
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 64 blocks is ~760s
ETH1_FOLLOW_DISTANCE: 0 # TODO look again


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536

# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Validator Stakes
# ---------------------------------------------------------------
# 2**5 * 10**9 (= 32,000,000,000) Gwei
MAX_EFFECTIVE_BALANCE: 32000000000
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000