version: "3.4"
services:
  init-geth:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-geth/geth:$GETH_VERSION
    container_name: lukso-geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init ./configs/genesis.json
  geth:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-geth/geth:$GETH_VERSION
    container_name: lukso-geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --ws
      --ws.api "net,eth,engine"
      --nat extip:$EXTERNAL_IP
      --bootnodes $GETH_BOOTSTRAP_NODE
      --networkid $GETH_NETWORK_ID
      --http
      --http.api "net,eth,engine"
      --http.addr "0.0.0.0"
      --verbosity $GETH_VERBOSITY
      --ipcdisable
      --port $GETH_PEER_PORT
      --http.port $GETH_HTTP_PORT
      --ethstats "${NODE_NAME}@${ETH_STATS_ADDRESS}"
      --miner.gaslimit 60000000
      --authrpc.jwtsecret /configs/jwtsecret
    network_mode: host

  lh_beacon:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-lighthouse/lighthouse:$LH_BEACON_VERSION
    container_name: lh_beacon
    depends_on:
      - geth
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
      - $LH_SCRIPTS_VOLUME:/scripts
    env_file: .env
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: sh /scripts/start_beacon_node.sh
    network_mode: host

  lh_account:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-lighthouse/lighthouse:$LH_BEACON_VERSION
    container_name: lh_account
    depends_on:
      - lh_beacon
    volumes:
      - $KEYSTORE_VOLUME:/keystores
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $LH_SCRIPTS_VOLUME:/scripts
    env_file: .env
    command: sh /scripts/create_wallet.sh
    network_mode: host

  lh_validator:
    image: europe-docker.pkg.dev/lks-lz-artifacts/docker-lighthouse/lighthouse:$LH_BEACON_VERSION
    container_name: lh_validator
    depends_on:
      - lh_beacon
      - lh_account
    volumes:
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $LH_SCRIPTS_VOLUME:/scripts
    env_file: .env
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: sh /scripts/start_validator.sh
    network_mode: host

  eth2stats-client:
    image: macht/eth2stats-client:v1.0.0
    container_name: eth2stats-client
    depends_on:
      - lh_beacon
    command: >
      run
      --beacon.type="v1"
      --eth2stats.node-name=$NODE_NAME
      --eth2stats.addr=$ETH_2_STATS_ADDRESS
      --eth2stats.tls=false
      --beacon.metrics-addr=http://127.0.0.1:5054/metrics
      --beacon.addr=http://127.0.0.1:5052
    network_mode: host