testnet-dir = "./configs/devnet/shared"
validators-dir = "./devnet-keystore/validators"
secrets-dir = "./devnet-keystore/validators"
beacon-nodes = "http://127.0.0.1:4000"
init-slashing-protection = true
http = true
http-port = 5062
metrics = true
metrics-address="127.0.0.1"
metrics-port=5057