testnet-dir = "./configs/testnet/shared"
datadir = "./testnet-data/consensus"
execution-jwt = "./configs/shared/secrets/jwt.hex"
execution-endpoint = "http://localhost:8551"
subscribe-all-subnets = true
listen-address = "0.0.0.0"
eth1 = true
http = true
http-address = "0.0.0.0"
http-port = 4000
enr-udp-port = 9000
enr-tcp-port = 9000
discovery-port = 9000
enable-private-discovery = true
enr-address = "0.0.0.0"
metrics = true
metrics-address = "0.0.0.0"
metrics-allow-origin = "*"
metrics-port = 5054
boot-nodes = 'enr:-MK4QHfHBBWZqSIxumgMmdC3zd7QyJD2shEXBhSKbay3aYwdAHrhb3lksHStJPk1tLoFOPaU4ELtaahRGUUpfm5tmhCGAYfiNvG0h2F0dG5ldHOIAAAAAAAAAACEZXRoMpBWKoojQgEABCoAAAAAAAAAgmlkgnY0gmlwhCKNxNSJc2VjcDI1NmsxoQOLhdJYX4WgjYXPw6GpCkuxnNWvM0KE_aeYzek95q2f-IhzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A'