# Network:
GENESIS_TIME: 1635149612
# Chain:
CHAIN_ID: 23
NETWORK_ID: 23
FORK_CHOICE: 0x83a55317
# Bootnodes:
PANDORA_BOOTNODES: ""
VANGUARD_BOOTNODES: ""
# Stats pages:
ETH1_STATS_URL: stats.pandora.l15.lukso.network
ETH1_STATS_APIKEY:
ETH2_STATS_URL: 34.141.156.125:9090
