chain = "mainnet"
networkid = 42

externalcl = true

miner.gaslimit = 42000000
miner.gasprice = 4200000000  # 4.2 Gwei
rpc.allow-unprotected-txs = true

datadir = "./mainnet-data/execution"
authrpc.jwtsecret = "./configs/shared/secrets/jwt.hex"
nat = "any"
ws = false
http = true
http.addr = "localhost"
http.api = "erigon,engine" # "eth,erigon,engine,debug,trace"
http.vhosts = "*"
authrpc.addr = "localhost"
authrpc.port = 8551
authrpc.vhosts = "*"

# ethstats = "<NODE_NAME>:<ETH_STATS_SECRET>@stats.execution.mainnet.lukso.network"

# Bootnodes
bootnodes = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.147.73.193:30303", "enode://3295490288f4ccbca74b3b0e5bf6fe25aee956eb8e0da9082008c2b75c3526dd75ec5f4770ee5467531e72a5cf0a631157c2721b511e42dfb5b6bdea507e6e78@34.32.192.211:30303"]
