chain = "mainnet"
networkid = 42

externalcl = true

miner.gaslimit = 42000000
miner.gasprice = 4200000000  # 4.2 Gwei
rpc.allow-unprotected-txs = true

datadir = "./mainnet-data/execution"
authrpc.jwtsecret = "./configs/shared/secrets/jwt.hex"
nat = "any"
ws = false
http = true
http.addr = "0.0.0.0"
http.api = "erigon,engine" # "eth,erigon,engine,debug,trace"
http.vhosts = "*"
authrpc.addr = "0.0.0.0"
authrpc.port = 8551
authrpc.vhosts = "*"

# ethstats = "${NODE_NAME}@${ETH_STATS_IP}"

# Bootnodes
bootnodes = []