chain = "mainnet"
networkid = 42

externalcl = true

miner.gaslimit = 42000000
miner.gasprice = 4200000000  # 4.2 Gwei

datadir = "./mainnet-data/execution"
"authrpc.jwtsecret" = "./configs/shared/secrets/jwt.hex"
nat = "any"
ws = false
http = true
"http.addr" = "0.0.0.0"
"http.api" = "erigon" # "eth,erigon,engine,debug,trace"
"http.vhosts" = "*"
"authrpc.addr" = "0.0.0.0"
"authrpc.port" = 8551
"authrpc.vhosts" = "*"

# ethstats = "${NODE_NAME}@${ETH_STATS_IP}"

# Bootnodes
bootnodes = ["enode://c2bb19ce658cfdf1fecb45da599ee6c7bf36e5292efb3fb61303a0b2cd07f96c20ac9b376a464d687ac456675a2e4a44aec39a0509bcb4b6d8221eedec25aca2@34.147.105.186:30303"]