name: Generate config with delay

on:
  workflow_dispatch:
    inputs:
      genesisTime:
        description: 'Genesis timestamp'
        required: true
        default: '0'
      delay:
        description: 'Delay time in minutes'
        required: false
        default: '0'
      network:
        description: 'Network'
        required: false
        default: 'l15'
      namespace:
        description: 'Namespace'
        required: false
        default: 'dev'
      requestUpgrade:
        description: 'Request l15-dev network upgrade with new genesis time. This ignores trigger for l15-staging and l15-prod'
        required: false
        default: 'false'

jobs:
  generateConfigs:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run config generator script
        env:
          NETWORK: ${{ github.event.inputs.network }}
          NAMESPACE: ${{ github.event.inputs.namespace }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
        
      
